### PR TITLE
debug relay test

### PR DESCRIPTION
**Pull request by vodkaslime**
Test PR to monitor test results

### CODE REVIEW

**Comment by vodkaslime** [comment]
```
ok  	github.com/pairmesh/pairmesh/internal/relay	0.107s
2022-04-06T07:20:36.393Z	INFO	Starting server
2022-04-06T07:20:36.393Z	INFO	Starting client
2022-04-06T07:20:36.393Z	INFO	Starting to send data
2022-04-06T07:20:36.393Z	INFO	Starting to validate data from chWait
2022-04-06T07:20:36.393Z	INFO	Current index in chWait is: 0
panic: test timed out after 10s
```
Client didn't event engage communication with server

**Comment by vodkaslime** [comment]
test

**Comment by vodkaslime** [comment]
```
ok  	github.com/pairmesh/pairmesh/internal/relay	0.097s
2022-04-06T07:25:32.595Z	INFO	Starting server
2022-04-06T07:25:32.595Z	INFO	Starting client
2022-04-06T07:25:32.596Z	INFO	Relay client noise protocol handshake is finished
2022-04-06T07:25:32.597Z	INFO	Starting to send data
2022-04-06T07:25:32.597Z	INFO	Starting to validate data from chWait
2022-04-06T07:25:32.597Z	INFO	Current index in chWait is: 0
2022-04-06T07:25:32.597Z	INFO	Got message from server: 0
2022-04-06T07:25:32.597Z	INFO	Feeding in chWait with index: 0
2022-04-06T07:25:32.597Z	INFO	Current index in chWait is: 1
2022-04-06T07:25:32.597Z	INFO	Got message from server: 1
2022-04-06T07:25:32.597Z	INFO	Feeding in chWait with index: 1
2022-04-06T07:25:32.597Z	INFO	Current index in chWait is: 2
2022-04-06T07:25:32.597Z	INFO	Got message from server: 2
2022-04-06T07:25:32.597Z	INFO	Feeding in chWait with index: 2
2022-04-06T07:25:32.597Z	INFO	Current index in chWait is: 3
2022-04-06T07:25:32.597Z	INFO	Current index in chWait is: 4
2022-04-06T07:25:32.601Z	INFO	Starting server
2022-04-06T07:25:32.601Z	WARN	Session connection transporter terminated	{"addr": "127.0.0.1:52550"}
2022-04-06T07:25:32.601Z	ERROR	Read connection failed	{"error": "read tcp 127.0.0.1:35089->127.0.0.1:52550: use of closed network connection"}
2022-04-06T07:25:32.601Z	INFO	Listener ready to close
2022-04-06T07:25:32.601Z	ERROR	Accept incoming connection failed	{"error": "accept tcp 127.0.0.1:35089: use of closed network connection"}
2022-04-06T07:25:32.601Z	ERROR	Read relay server message failed	{"error": "EOF"}
2022-04-06T07:25:32.601Z	WARN	Client connection transporter terminated	{"addr": "127.0.0.1:35089"}
2022-04-06T07:25:32.602Z	ERROR	Write message failed	{"error": "write tcp 127.0.0.1:52550->127.0.0.1:35089: use of closed network connection"}
--- FAIL: TestRelayNetworkFailure (1.00s)
    relay_test.go:197: 
        	Error Trace:	relay_test.go:197
        	Error:      	Expected nil, but got: &net.OpError{Op:"dial", Net:"tcp", Source:net.Addr(nil), Addr:(*net.TCPAddr)(0xc000076[75](https://github.com/pairmesh/pairmesh/runs/5846643945?check_suite_focus=true#step:4:75)0), Err:(*os.SyscallError)(0xc00005[83](https://github.com/pairmesh/pairmesh/runs/5846643945?check_suite_focus=true#step:4:83)60)}
        	Test:       	TestRelayNetworkFailure
    relay_test.go:200: 
        	Error Trace:	relay_test.go:200
        	Error:      	Should be true
        	Test:       	TestRelayNetworkFailure
```

**Comment by hi-windy** [comment]
@vodkaslime We can refactor the test case if it's not well-design.

**Comment by vodkaslime** [comment]
Sure maybe we need to refactor rthe test cases, or maybe it's sessions or clients

**Comment by vodkaslime** [comment]
```
ok  	github.com/pairmesh/pairmesh/internal/relay	0.136s
2022-04-06T07:51:41.610Z	INFO	Starting server
2022-04-06T07:51:41.610Z	INFO	Starting client
2022-04-06T07:51:41.610Z	INFO	Starting to send data
2022-04-06T07:51:41.610Z	INFO	Added data to write queue
2022-04-06T07:51:41.610Z	INFO	Added data to write queue
2022-04-06T07:51:41.610Z	INFO	Added data to write queue
2022-04-06T07:51:41.610Z	INFO	Added data to write queue
2022-04-06T07:51:41.610Z	INFO	Added data to write queue
2022-04-06T07:51:41.610Z	INFO	Starting to validate data from chWait
2022-04-06T07:51:41.610Z	INFO	Current index in chWait is: 0
panic: test timed out after 10s
```

**Comment by vodkaslime** [comment]
```
ok  	github.com/pairmesh/pairmesh/internal/relay	0.0[84](https://github.com/pairmesh/pairmesh/runs/5847186562?check_suite_focus=true#step:4:84)s
2022-04-06T08:07:50.734Z	INFO	Starting server
2022-04-06T08:07:50.734Z	INFO	Starting client
2022-04-06T08:07:50.734Z	INFO	Starting to send data
2022-04-06T08:07:50.734Z	INFO	Added data to write queue
2022-04-06T08:07:50.734Z	INFO	Added data to write queue
2022-04-06T08:07:50.734Z	INFO	Added data to write queue
2022-04-06T08:07:50.734Z	INFO	Added data to write queue
2022-04-06T08:07:50.734Z	INFO	Added data to write queue
2022-04-06T08:07:50.734Z	INFO	Starting to validate data from chWait
2022-04-06T08:07:50.734Z	INFO	Current index in chWait is: 0
panic: test timed out after 10s
```
Looks like the client side Read() and Write() loops are not even spawned. Need to double check

**Comment by vodkaslime** [comment]
```
ok  	github.com/pairmesh/pairmesh/internal/relay	0.107s
2022-04-06T08:20:49.6[85](https://github.com/pairmesh/pairmesh/runs/5847365620?check_suite_focus=true#step:4:85)Z	INFO	Starting server
2022-04-06T08:20:49.685Z	INFO	Starting client
2022-04-06T08:20:49.685Z	INFO	Starting to connect from test case
2022-04-06T08:20:49.685Z	INFO	Starting to connect from client side
2022-04-06T08:20:49.6[86](https://github.com/pairmesh/pairmesh/runs/5847365620?check_suite_focus=true#step:4:86)Z	INFO	Starting to send data
2022-04-06T08:20:49.686Z	INFO	Added data to write queue
2022-04-06T08:20:49.686Z	INFO	Added data to write queue
2022-04-06T08:20:49.686Z	INFO	Added data to write queue
2022-04-06T08:20:49.686Z	INFO	Added data to write queue
2022-04-06T08:20:49.686Z	INFO	Added data to write queue
2022-04-06T08:20:49.686Z	INFO	Starting to validate data from chWait
2022-04-06T08:20:49.686Z	INFO	Current index in chWait is: 0
panic: test timed out after 10s
```
Client side connection not even reached the point of spawning Read and Write

**Comment by vodkaslime** [comment]
```
ok  	github.com/pairmesh/pairmesh/internal/relay	0.096s
2022-04-06T08:27:04.[74](https://github.com/pairmesh/pairmesh/runs/5847449904?check_suite_focus=true#step:4:74)2Z	INFO	Starting server
2022-04-06T08:27:04.742Z	INFO	Starting client
2022-04-06T08:27:04.742Z	INFO	Starting to connect from test case
2022-04-06T08:27:04.742Z	INFO	Starting to connect from client side
2022-04-06T08:27:04.742Z	INFO	Before dialing
2022-04-06T08:27:04.742Z	INFO	Error dialing
2022-04-06T08:27:04.742Z	INFO	Starting to send data
2022-04-06T08:27:04.742Z	INFO	Added data to write queue
2022-04-06T08:27:04.742Z	INFO	Added data to write queue
2022-04-06T08:27:04.742Z	INFO	Added data to write queue
2022-04-06T08:27:04.742Z	INFO	Added data to write queue
2022-04-06T08:27:04.742Z	INFO	Added data to write queue
2022-04-06T08:27:04.742Z	INFO	Starting to validate data from chWait
2022-04-06T08:27:04.742Z	INFO	Current index in chWait is: 0
panic: test timed out after 10s
```
Got error dialing actually

**Comment by vodkaslime** [comment]
```
ok  	github.com/pairmesh/pairmesh/internal/relay	0.103s
2022-04-06T08:31:19.471Z	INFO	Starting server
2022-04-06T08:31:19.471Z	INFO	Starting client
2022-04-06T08:31:19.471Z	INFO	Starting to connect from test case
2022-04-06T08:31:19.471Z	INFO	Starting to connect from client side
2022-04-06T08:31:19.471Z	INFO	Before dialing
2022-04-06T08:31:19.472Z	INFO	Error dialing: dial tcp 127.0.0.1:34407: connect: connection refused
2022-04-06T08:31:19.472Z	INFO	Starting to send data
2022-04-06T08:31:19.472Z	INFO	Added data to write queue
2022-04-06T08:31:19.472Z	INFO	Added data to write queue
2022-04-06T08:31:19.472Z	INFO	Added data to write queue
2022-04-06T08:31:19.472Z	INFO	Added data to write queue
2022-04-06T08:31:19.472Z	INFO	Added data to write queue
2022-04-06T08:31:19.472Z	INFO	Starting to validate data from chWait
2022-04-06T08:31:19.472Z	INFO	Current index in chWait is: 0
panic: test timed out after 10s
```
Oh connection refused

**Comment by vodkaslime** [comment]
```
ok  	github.com/pairmesh/pairmesh/internal/relay	0.117s
2022-04-06T08:43:53.1[90](https://github.com/pairmesh/pairmesh/runs/5847677355?check_suite_focus=true#step:4:90)Z	INFO	Starting server
2022-04-06T08:43:53.1[91](https://github.com/pairmesh/pairmesh/runs/5847677355?check_suite_focus=true#step:4:91)Z	INFO	Starting client
2022-04-06T08:43:53.191Z	INFO	Starting to connect from test case
2022-04-06T08:43:53.191Z	INFO	Starting to connect from client side
2022-04-06T08:43:53.191Z	INFO	Before dialing
2022-04-06T08:43:53.191Z	INFO	Listening from server side with port: 127.0.0.1:37125
2022-04-06T08:43:53.191Z	INFO	Accepting from server side
2022-04-06T08:43:53.191Z	INFO	Error dialing: dial tcp 127.0.0.1:37125: connect: connection refused
2022-04-06T08:43:53.191Z	INFO	The err is indeed nil: false
2022-04-06T08:43:53.191Z	INFO	Starting to send data
2022-04-06T08:43:53.191Z	INFO	Added data to write queue
2022-04-06T08:43:53.191Z	INFO	Added data to write queue
2022-04-06T08:43:53.191Z	INFO	Added data to write queue
2022-04-06T08:43:53.191Z	INFO	Added data to write queue
2022-04-06T08:43:53.191Z	INFO	Added data to write queue
2022-04-06T08:43:53.191Z	INFO	Starting to validate data from chWait
2022-04-06T08:43:53.191Z	INFO	Current index in chWait is: 0
panic: test timed out after 10s
```
Client trying to connect before server side is ready to accept. Since the serve functionality from server side is spawned in goroutine, there is no elegant way to precisely "wait" for it to get ready. A feasible solution is just to sleep to wait for a sec.

**Comment by vodkaslime** [comment]
But why was this error not caught?

**Comment by vodkaslime** [comment]
```
ok  	github.com/pairmesh/pairmesh/internal/relay	0.[104](https://github.com/pairmesh/pairmesh/runs/5847792532?check_suite_focus=true#step:4:104)s
2022-04-06T08:52:02.226Z	INFO	Starting server
2022-04-06T08:52:02.226Z	INFO	Listening from server side with port: 127.0.0.1:42207
2022-04-06T08:52:02.226Z	INFO	Starting client
2022-04-06T08:52:02.226Z	INFO	Starting to connect from test case
2022-04-06T08:52:02.226Z	INFO	Starting to connect from client side
2022-04-06T08:52:02.226Z	INFO	Before dialing
2022-04-06T08:52:02.226Z	INFO	Accepting from server side
2022-04-06T08:52:02.227Z	INFO	Accepting from server side
2022-04-06T08:52:02.228Z	INFO	After dialing
2022-04-06T08:52:02.228Z	INFO	Starting to spawn client Read and Write
2022-04-06T08:52:02.228Z	INFO	Started client read job
2022-04-06T08:52:02.228Z	INFO	Started client write job
2022-04-06T08:52:02.228Z	INFO	Got data from chWrite
2022-04-06T08:52:02.228Z	INFO	Got data from server side to read
2022-04-06T08:52:02.228Z	INFO	Got data from server side to chRead
2022-04-06T08:52:02.229Z	INFO	Got data from server side to write
2022-04-06T08:52:02.229Z	INFO	Got data from buffer
2022-04-06T08:52:02.229Z	INFO	Put data to chRead
2022-04-06T08:52:02.229Z	INFO	Relay client noise protocol handshake is finished
2022-04-06T08:52:02.229Z	INFO	The err is indeed nil: true
2022-04-06T08:52:02.229Z	INFO	Starting to send data
2022-04-06T08:52:02.229Z	INFO	Added data to write queue
2022-04-06T08:52:02.229Z	INFO	Added data to write queue
2022-04-06T08:52:02.229Z	INFO	Added data to write queue
2022-04-06T08:52:02.229Z	INFO	Added data to write queue
2022-04-06T08:52:02.229Z	INFO	Added data to write queue
2022-04-06T08:52:02.229Z	INFO	Starting to validate data from chWait
2022-04-06T08:52:02.229Z	INFO	Current index in chWait is: 0
2022-04-06T08:52:02.229Z	INFO	Writen data
2022-04-06T08:52:02.229Z	INFO	Got data from chWrite
2022-04-06T08:52:02.229Z	INFO	Got data from server side to read
2022-04-06T08:52:02.229Z	INFO	Got data from server side to chRead
2022-04-06T08:52:02.229Z	INFO	Got message from server: 0
2022-04-06T08:52:02.229Z	INFO	Got data from server side to write
2022-04-06T08:52:02.229Z	INFO	Got data from buffer
2022-04-06T08:52:02.229Z	INFO	Put data to chRead
2022-04-06T08:52:02.229Z	INFO	Feeding in chWait with index: 0
2022-04-06T08:52:02.229Z	INFO	Current index in chWait is: 1
2022-04-06T08:52:02.229Z	INFO	Writen data
2022-04-06T08:52:02.229Z	INFO	Got data from chWrite
2022-04-06T08:52:02.230Z	INFO	Got data from server side to read
2022-04-06T08:52:02.230Z	INFO	Got data from server side to chRead
2022-04-06T08:52:02.230Z	INFO	Got message from server: 1
2022-04-06T08:52:02.230Z	INFO	Got data from server side to write
2022-04-06T08:52:02.230Z	INFO	Got data from buffer
2022-04-06T08:52:02.230Z	INFO	Put data to chRead
2022-04-06T08:52:02.230Z	INFO	Feeding in chWait with index: 1
2022-04-06T08:52:02.230Z	INFO	Current index in chWait is: 2
2022-04-06T08:52:02.230Z	INFO	Writen data
2022-04-06T08:52:02.230Z	INFO	Got data from chWrite
2022-04-06T08:52:02.230Z	INFO	Got data from server side to read
2022-04-06T08:52:02.230Z	INFO	Got data from server side to chRead
2022-04-06T08:52:02.230Z	INFO	Got message from server: 2
2022-04-06T08:52:02.230Z	INFO	Got data from server side to write
2022-04-06T08:52:02.230Z	INFO	Got data from buffer
2022-04-06T08:52:02.230Z	INFO	Put data to chRead
2022-04-06T08:52:02.230Z	INFO	Feeding in chWait with index: 2
2022-04-06T08:52:02.230Z	INFO	Current index in chWait is: 3
2022-04-06T08:52:02.230Z	INFO	Writen data
2022-04-06T08:52:02.230Z	INFO	Got data from chWrite
2022-04-06T08:52:02.230Z	INFO	Got data from server side to read
2022-04-06T08:52:02.230Z	INFO	Got data from server side to chRead
2022-04-06T08:52:02.230Z	INFO	Got message from server: 3
2022-04-06T08:52:02.230Z	INFO	Got data from server side to write
2022-04-06T08:52:02.230Z	INFO	Got data from buffer
2022-04-06T08:52:02.230Z	INFO	Put data to chRead
2022-04-06T08:52:02.231Z	INFO	Feeding in chWait with index: 3
2022-04-06T08:52:02.231Z	INFO	Current index in chWait is: 4
2022-04-06T08:52:02.231Z	INFO	Writen data
2022-04-06T08:52:02.231Z	INFO	Got data from chWrite
2022-04-06T08:52:02.231Z	INFO	Writen data
2022-04-06T08:52:02.231Z	INFO	Got data from server side to read
2022-04-06T08:52:02.231Z	INFO	Got data from server side to chRead
2022-04-06T08:52:02.231Z	INFO	Got message from server: 4
2022-04-06T08:52:02.231Z	INFO	Got data from server side to write
2022-04-06T08:52:02.231Z	INFO	Got data from buffer
2022-04-06T08:52:02.231Z	INFO	Put data to chRead
2022-04-06T08:52:02.231Z	INFO	Feeding in chWait with index: 4
--- FAIL: TestRelay (0.01s)
    relay_test.go:48: 
        	Error Trace:	relay_test.go:48
        	Error:      	Should be true
        	Test:       	TestRelay
    relay_test.go:[112](https://github.com/pairmesh/pairmesh/runs/5847792532?check_suite_focus=true#step:4:112): 
        	Error Trace:	relay_test.go:112
        	Error:      	Should be true
        	Test:       	TestRelay
```
Oh, in golang, the assertion failure doesn't even stop you there. It keeps on running the test until it finishes, and then tell you that you just got an error...

**Review by hi-windy — APPROVED** [review]

**Pull request merged**
